### ISSUE TITLE
TypeError: 'function' object is not subscriptable

### ISSUE THREAD

**Issue by w0203j** [delfick/secrets_ansible#1]
Trying to run the below having issues. Are you able to help? 
```
$ ./bespin.sh generate_secrets staging
```

```
File "/Users/jun.wang/project/fake path/deploy/files/ansible/roles/secrets/bespin/scripts.py", line 46, in generate_secret
    key_id = stack.vars['KMSMasterKey'].resolve()
TypeError: 'function' object is not subscriptable
```

**Comment by delfick** [comment]
you seem to have a version that's different than the one in this repo, but that error is because the vars on the stack is a callable (https://github.com/delfick/bespin/blob/master/bespin/option_spec/bespin_specs.py#L299) (the delayed spec returns a function)

so just change your script to say `stack.vars()['KMSMasterKey'].resolve()`

**Comment by w0203j** [comment]
Mate you are so quick! 

So I am running an old version of this `secrets_ansible` than this repo?

**Comment by delfick** [comment]
it's possible that I made changes to it in the project you're working in but never migrated those changes to this repo.

**Comment by w0203j** [comment]
Thanks!

Running into another issue any idea?
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Something went wrong! -- BadOptionFormat
	"Bad option format. Can't find key in options"	chain=['stacks.app.vars.artifact_location', '__stack__.artifacts.main.upload_to']	key=__stack__.artifacts.main.upload_to	source=[]
```

**Comment by delfick** [comment]
so does your stack have an artifacts.main.upload_to option?

**Comment by w0203j** [comment]
This is all I can find in `bespin.yml`:

```
stacks:
    app:
        vars:
        artifact_location: "{__stack__.artifacts.main.upload_to}"
```

**Comment by delfick** [comment]
are you sure you don't have the `main` artifact defined somewhere?

**Comment by delfick** [comment]
like if you don't have an artifact for your bespin build, then you can probably just remove the artifact_location variable

**Comment by w0203j** [comment]
Hmmmm what I don't get is how do I get errors like this when I try to call `key_id = stack.vars()['KMSMasterKey'].resolve()`

**Comment by delfick** [comment]
Because when you call vars() it's getting all the variables, which involves
formatting them all, which in turn tries to format the artifact_location
variable, which then fails cause you don't have the option it's referring
to.

**Comment by delfick** [comment]
The call to resolve happens on either a StaticVariable object or a DynamicVariable object as determined by https://github.com/delfick/bespin/blob/master/bespin/option_spec/stack_specs.py#L34-L39; which happens after the field has been formatted.

**Comment by w0203j** [comment]
Thanks.

Got passed that point by replacing the line in script.py with the below line:
`key_id = collector.configuration["environments"][environment]["vars"]["KMSMasterKey"]`
